//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbs
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogInfo
    {
        public string title { get; set; }
        public Nullable<int> blogId { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> dateOfCreation { get; set; }
        public string empEmailId { get; set; }
        public string blogUrl { get; set; }
    }
}
