//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbs
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public string emailId { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfJoin { get; set; }
        public Nullable<int> passcode { get; set; }
    }
}
